config/routes.rb
Rails.application.routes.draw do
  root to: "application#home"
  resources :articles
  get "signup", to: "users#new"
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "delete", to: "sessions#destroy"
  resources :users, except: [:new]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
   belongs_to :user
   validates :title, presence: true, length: {minimum:2, maximum:50}
   validates :description, presence: true, length: {minimum:10, maximum:60}
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  has_many :articles, dependent: :destroy
  validates :username, presence: true,
                       uniqueness: { case_sensitive: false },
                       length: { mimum: 3, maximum: 25 }
  VALID_EMAIL_REGEX = URI::MailTo::EMAIL_REGEXP
  validates :email, presence: true,
                    uniqueness: { case_sensitive: false },
                    length: { maximum: 105 },
                    format: { with: VALID_EMAIL_REGEX }
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  def home
    redirect_to articles_path if logged_in?
  end

  # Metodas gali buti naudojamas tiek controleryje tiek view'e. Helperis pasiekia tik view
  helper_method :current_user, :logged_in?

  def current_user
    # jei yra current user grazinam, jeigu ne tada querinam
    @current_user || User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    # convertinimas kintamojo i bool
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:alert] = "You must be logged in to perform this action"
      redirect_to login_path
    end
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :require_user, except: [:show, :index]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def show
  end

  def destroy
    @article.destroy
    # rails 7 needs to set status
    redirect_to articles_path, status: :see_other
  end

  def index
    @articles = Article.paginate(page: params[:page], per_page: 2)
  end

  def new
    @article = Article.new()
  end

  def edit
  end

  def update
    if @article.update(article_params)
      flash[:notice] = "Article was updated successfully"
      redirect_to @article
    else
      render "edit"
    end
  end

  def create
    @article = Article.new(article_params)
    @article.user = current_user
    if @article.save
      flash[:notice] = "Created"
      redirect_to @article
      # redirect_to article_path(@article.id)
    else
      render "new"
    end
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :description)
  end

  def require_same_user
    if current_user != @article.user || !current_user.admin?
      flash[:alert] = "You can only work with your own articles"
      redirect_to @article
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new
    end

    def create
        if session[:user_id]
            flash[:notice] = "Alredy logged in"
        end

        user = User.find_by(email: params[:session][:email].downcase)
        if user && user.authenticate(params[:session][:password])
            session[:user_id] = user.id
            flash[:notice] = "Logged in succesfully"
            redirect_to user
        else
            flash.now[:alert] = "Invalid credentials"
            render 'new'
        end
    end

    def destroy
        session[:user_id] = nil
        flash[:notice] = "Logged out"
        redirect_to root_path
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_user, only: [:edit, :update, :show, :destroy]
  before_action :require_user, only: [:edit, :update]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def new
    @user = User.new()
  end

  def index
    @users = User.paginate(page: params[:page], per_page: 2)
  end

  def show
    @articles = @user.articles.paginate(page: params[:page], per_page: 2)
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Welcome to the alpha blog #{@user.username}, you have registered"
      redirect_to articles_path
    else
      render "new"
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:notice] = "Your account information was successfully updated"
      redirect_to @user
    else
      render "edit"
    end
  end

  def destroy
    @user.destroy
    session[:user_id] = nil if @user == current_user
    flash[:notice] = "Account and all articles deleted"
    redirect_to root_path, status: :see_other
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def require_same_user
    if current_user != @user && current_user.admin?
      flash[:alert] = "You can edit only your account"
      redirect_to @user
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user, options = { size: 80 })
    email = user.email.downcase
    hash = Digest::MD5.hexdigest(email)
    size = options[:size]
    image_src = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
    image_tag(image_src, alt: user.username)
  end

end

app/views/application/home.html.erb
<%= link_to 'View Articles', articles_path %>
<br>
<%= link_to 'Sign up!', signup_path %>

app/views/articles/_article.html.erb
<table>
    <thead>
        <tr>
            <th>Title</th>
            <th>Description</th>
            <th>Author</th>
            <th colspan="3">Action</th>
        <tr>
    </thead>
    <tbody>
        <% @articles.each do |article| %>
            <tr>
                <td><%= article.title %></td>
                <td><%= article.description %></td>
                <% if article.user %>
                    <td><%= link_to article.user.username, user_path(article.user) %></td>
                <% else %>
                    <td><%= article.user.username %></td>
                <% end %>
                <td><%= link_to "View", article_path(article) %></td>
                <% if logged_in? && article.user == current_user || current_user.admin? %>
                    <td><%= link_to "Edit", edit_article_path(article) %></td>
                    <td><%= link_to "Delete", article_path(article), data: { "turbo-method": :delete, "turbo-confirm": "Are you sure?" } %></td>
                <% end %>
            </tr>
        <% end %>
    </tbody>
</table>

app/views/articles/create.html.erb
<h1>Create</h1>

app/views/articles/edit.html.erb
<h1>Edit</h1>

<%= render 'articles/form/form' %>

<%= link_to 'View All', articles_path %>

app/views/articles/form/_form.html.erb
<%= render 'articles/form/form_errors' %>

<%= form_with(model: @article, local: true, data: {turbo: false}) do |f| %>

    <p>
        <%= f.label :title %> <br>
        <%= f.text_field :title %>
    </p>

    <p>
        <%= f.label :description %> <br>
        <%= f.text_area :description %> 
    </p>

    <p>
        <%= f.submit %>
    </p>

<% end %>

app/views/articles/form/_form_errors.html.erb
<% if @article.errors.any? %>
    <h2>The following errors prevented article from being edited</h2>
    <ul>
        <% @article.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
    </ul>
<% end %>

app/views/articles/index.html.erb
<h1>Article List</h1>

<%= will_paginate @articles, :container => false %>

<%= render 'article' %>
<p>
    <% if logged_in? %>
    <%= link_to 'Add', new_article_path %>
    <%= link_to 'Home', root_path %>
    <% end %>
<p>

<%= will_paginate @articles, :container => false %>

app/views/articles/new.html.erb
<h1>New</h1>

<%= render 'articles/form/form' %>

<%= link_to 'View All', articles_path %>

app/views/articles/show.html.erb
<h1>Article show</h1>

<p><b>Author:</b> <%= @article.user.username %></p>
<p><b>Title: </b><%= @article.title %></p>
<p><b>Description: </b><%= @article.description %></p>

<p>
    <% if logged_in? && current_user == @article.user || current_user.admin? %>
        <%= link_to "Edit", edit_article_path(@article) %>
        <%= link_to "Delete", article_path(@article), data: { "turbo-method": :delete, "turbo-confirm": "Are you sure?" } %>
    <% end %>
    <%= link_to "View All", articles_path %>
</p>

<%= link_to gravatar_for(@article.user), user_path(@article.user) %>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
    <%= msg %>
<% end %>

app/views/layouts/_navigation.html.erb
<div>
<p>
<%= link_to "Home", root_path, class: "navbarItem" %>
<%= link_to "Articles", articles_path, class: "navbarItem" %>
<% if logged_in? %>
    Profile <%= link_to current_user.username, user_path(current_user) %>
    <%= link_to "New Article", new_article_path, class: "navbarItem" %>
<% end %>
<%= link_to "Bloggers", users_path, class: "navbarItem" %>
<% if logged_in? %>
    <%= "Admin" if current_user.admin?%>
    <%= link_to current_user.username, user_path(current_user), class: "navbarItem" %>
    <%= link_to "Logout", delete_path, class: "navbarItem", data: { "turbo-method": :delete } %>
    <%= link_to "Delete profile", user_path(current_user), class: "navbarItem", data: { "turbo-method": :delete } %>

<% else %>
    <%= link_to "Login", login_path, class: "navbarItem" %>
    <%= link_to "Sign Up", signup_path, class: "navbarItem" %>
<% end %>

</p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <%= render 'layouts/navigation' %>
  <%= render 'layouts/messages' %>
    <%= yield %>
  </body>
</html>

app/views/users/_user.html.erb
<table>
    <thead>
        <tr>
            <th>Name</th>
            <th>Email</th>
            <th>Articles</th>
            <th>Joined</th>
            <th colspan="3">Action</th>
        <tr>
    </thead>
    <tbody>
        <% @users.each do |user| %>
            <tr>
                <td><%= user.username %></td>
                <td><%= user.email %></td>
                <td><%= user.articles.length %></td>
                <td><%= user.created_at %></td>
                <td><%= link_to "View", user_path(user) %></td>
                <% if logged_in? %>
                    <% if user == current_user || current_user.admin?%>
                        <td><%= link_to "Edit", edit_user_path(user) %></td>
                        <td><%= link_to "Delete", user_path(user), data: { "turbo-method": :delete, "turbo-confirm": "Sure?" } %></td>
                    <% end %>
                <% end %>
            </tr>
        <% end %>
    </tbody>
</table>

app/views/users/edit.html.erb
<h1>Edit your profile</h1>

<%= render 'users/form/form' %>

app/views/users/form/_form.html.erb
<%= render "users/form/form_errors" %>

<%= form_with(model: @user, local: true, data: { turbo: false }) do |f| %>

    <p>
        <%= f.label :username %> <br>
        <%= f.text_field :username, placeholder: "Enter a username" %>
    </p>

    <p>
        <%= f.label :email %> <br>
        <%= f.email_field :email, placeholder: "Enter your email" %> 
    </p>
 
    <p>
        <%= f.label :password %> <br>
        <%= f.password_field :password %> 
    </p>

    <p>
        <%= f.submit(@user.new_record? ? "Sign up" : "Update") %>
    </p>

<% end %>

app/views/users/form/_form_errors.html.erb
<% if @user.errors.any? %>
    <h2>The following errors prevented user from being edited</h2>
    <ul>
        <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
    </ul>
<% end %>

app/views/users/index.html.erb
<h1>Users</h1>

<%= will_paginate @articles, :container => false %>

<%= render 'user' %>

<%= will_paginate @articles, :container => false %>


<p>
    <%= link_to 'Home', root_path %>
<p>

app/views/users/new.html.erb
<h1>Create user</h1>

<%= render 'users/form/form' %>

app/views/users/show.html.erb
<h1><%= @user.username %>'s profile</h1>
<% # galima ir su skliausteliais pasirodo :) %>
<%= gravatar_for(@user, size: 200) %>

<div>
    <% if logged_in? %>
        <% if @user == current_user %>
            <%= link_to "Edit your profile", edit_user_path(@user), class: "btn" %>
        <% end %>
        <% if current_user.admin? %>
            <%= link_to "Delete_user", user_path(@user), class: "navbarItem", data: { "turbo-method": :delete } %>
        <% end %>
    <% end %>
</div>

<h3> User articles: </h3>

<%= will_paginate @articles, :container => false %>

<%= render "articles/article" %>

<%= will_paginate @articles, :container => false %>